package ai.shreds.domain.services;

import ai.shreds.domain.entities.DomainMfaChallengeEntity;
import ai.shreds.domain.entities.DomainSecuritySettingsEntity;
import ai.shreds.domain.exceptions.DomainInvalidTokenException;
import ai.shreds.domain.ports.DomainInputPortMfa;
import ai.shreds.domain.ports.DomainOutputPortCryptoService;
import ai.shreds.domain.ports.DomainOutputPortMfaChallengeRepository;
import ai.shreds.domain.ports.DomainOutputPortSecurityRepository;
import ai.shreds.shared.enums.SharedMfaMethodEnum;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

@Service
public class DomainMfaService implements DomainInputPortMfa {

    private final DomainOutputPortMfaChallengeRepository challengeRepository;
    private final DomainOutputPortSecurityRepository securityRepository;
    private final DomainOutputPortCryptoService cryptoService;

    public DomainMfaService(
            DomainOutputPortMfaChallengeRepository challengeRepository,
            DomainOutputPortSecurityRepository securityRepository,
            DomainOutputPortCryptoService cryptoService) {
        this.challengeRepository = challengeRepository;
        this.securityRepository = securityRepository;
        this.cryptoService = cryptoService;
    }

    @Override
    public DomainMfaChallengeEntity generateMfaChallenge(String accountId, SharedMfaMethodEnum method) {
        // Generate verification code based on method
        String verificationCode;
        switch (method) {
            case SMS:
            case EMAIL:
                // Generate 6-digit numeric code
                verificationCode = String.format("%06d", (int) (Math.random() * 1000000));
                break;
            case TOTP:
                // For TOTP, the code is generated by the authenticator app
                // Here we just create a placeholder challenge that will be verified differently
                verificationCode = "TOTP_PLACEHOLDER";
                break;
            default:
                throw new IllegalArgumentException("Unsupported MFA method: " + method);
        }

        // Hash the verification code for storage
        String hashedCode = cryptoService.hashToken(verificationCode);

        // Create MFA challenge entity
        DomainMfaChallengeEntity challenge = new DomainMfaChallengeEntity(
            UUID.randomUUID(),
            UUID.fromString(accountId),
            hashedCode,
            method,
            Instant.now().plus(5, ChronoUnit.MINUTES), // 5 minutes expiration
            false,
            Instant.now()
        );

        return challengeRepository.save(challenge);
    }

    @Override
    public boolean verifyMfaCode(String challengeId, String code) {
        // Find the challenge
        DomainMfaChallengeEntity challenge = challengeRepository.findById(challengeId);
        if (challenge == null) {
            throw new DomainInvalidTokenException("Invalid challenge ID");
        }

        // Check if challenge is valid (not expired or used)
        if (!challenge.isValid()) {
            return false;
        }

        // Verify the code based on method
        boolean isValid = false;
        switch (challenge.getMethod()) {
            case SMS:
            case EMAIL:
                // Hash the provided code and compare with stored hash
                String hashedProvidedCode = cryptoService.hashToken(code);
                isValid = challenge.getChallengeCodeHash().equals(hashedProvidedCode);
                break;
            case TOTP:
                // For TOTP, implement TOTP verification logic here
                // This is a simplified implementation
                isValid = verifyTotpCode(challenge.getAccountId().toString(), code);
                break;
        }

        if (isValid) {
            // Mark challenge as used
            challenge.markAsUsed();
            challengeRepository.markAsUsed(challengeId);
        }

        return isValid;
    }

    @Override
    public boolean isMfaRequired(String accountId) {
        DomainSecuritySettingsEntity securitySettings = securityRepository.findByAccountId(accountId);
        return securitySettings != null && securitySettings.isMfaEnabled();
    }

    private boolean verifyTotpCode(String accountId, String code) {
        // Simplified TOTP verification
        // In a real implementation, you would use a proper TOTP library
        // and verify against the user's secret key
        
        // For now, accept any 6-digit numeric code as valid
        return code != null && code.matches("\\d{6}");
    }
}
